
cc_library(
        name = "lib_a",
        srcs = ["lib_a.cpp"],
)

cc_library(
        name = "lib_b",
        deps = ["lib_a"],
        srcs = ["lib_b.cpp"],
)

cc_library(
        name = "lib_c",
        deps = ["lib_a"],
        srcs = ["lib_c.cpp"],
)
